### ISSUE TITLE
don't show kanban menu button on all git domains

### ISSUE THREAD

**Issue by fazlerabbi37** [funktechno/git-kanban-enhanced-chrome-extension#19]
This issue is:

- [x] Bug report
- [ ] Feature request
- [ ] Improvement

### Steps to reproduce
1. install Self Hosted plugin
2. add a specific Gitea instance as host
3. visit site like GitHub, Bitbucket or GitLab

### Actual behavior
kanban menu button shows in all GitHub, Bitbucket and GitLab instace where it is unnecessary and unpleasant. 

### Expected behavior
kanban menu button should only show in those domains that are added to plugin.

### Configuration

- Extension Id Used (self hosted vs simple): Self Hosted (ambmbdjjhloinbjadfgfmenihmfmahmk)
- Is the domain a root or a subdirectory path ( e.g. gitea.mywebsite.com or mywebsite.com/gitea): N/A
- Site Access in More Tools > Extensions, Extension Details (all sites, On specific sites - whitelist list): N/A
- Chrome version: 75.0.3770.142 (Official Build)
- OS: Ubuntu 18.04
- Browser: Chrome

**Comment by lastlink** [comment]
This should be fairly easy, I guess for self hosted make it opt in, for the non self hosted they are all on by default.

**Comment by fazlerabbi37** [comment]
> This should be fairly easy, I guess for self hosted make it opt in, for the non self hosted they are all on by default.

Hoping to see in implemented soon!

---

Though non of them are functional but for GitHub and GitLab it integrates seamlessly with the design while for Bitbucket it is just disorienting. 

GitHub:

![image](https://user-images.githubusercontent.com/11360512/61729502-2bec0380-ad99-11e9-83cd-0d02c52e8fd2.png)

GitLab:

![image](https://user-images.githubusercontent.com/11360512/61729538-41612d80-ad99-11e9-81ab-9d4f92c0d20f.png)

Bitbucket:

![image](https://user-images.githubusercontent.com/11360512/61729558-50e07680-ad99-11e9-93cb-55c2ef74cbc9.png)

**Comment by lastlink** [comment]
it used to fit in bitbucket, the issue is that bitbucket dynamically updates their class names with hashes and random characters, I need to update my css selectors to take this into account. probably something similar to `[class*="partialname"]`

**Comment by lastlink** [comment]
I'd like this to match the design of the git server as much as possible so I try reusing their css classes. bitbucket is much messier b/c I also have to parse and store and reuse their classes dynamically
