### ISSUE TITLE
Firefox

### ISSUE THREAD

**Issue by lonix1** [funktechno/git-kanban-enhanced-chrome-extension#20]
Firstly, well done! This is an incredibly useful and promising extension.

Any plans to support firefox?

**Comment by lastlink** [comment]
it's open sourced your welcome to look into it, It's not something I'm prioritizing now though. I can publish it if it becomes stable.

**Comment by lonix1** [comment]
Any reason you went with chrome plugins instead of webextensions? From what I understand webextensions work on all browsers.

**Comment by lastlink** [comment]
I'm not familiar with this term is it a different type of format. There is some documentation on porting chrome extensions to firefox.

**Comment by lonix1** [comment]
some bakground for WebExtensions:
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions
https://developer.chrome.com/extensions

**Comment by lastlink** [comment]
from what I can tell the best thing is to use the webextension api rather than the chrome api to make it cross platform. I probably could try changing my function calls to see if I can still replicate my functionality.

e.g. instead of `chrome.tabs` use `browser.tabs`

https://github.com/funktechno/git-kanban-enhanced-chrome-extension/blob/master/src/backend/index.js

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Working_with_the_Tabs_API

I don't have a lot of chrome api calls, but I can work on converting these over.

**Comment by lonix1** [comment]
Sounds great, I'll be the first beta tester! :)

**Comment by lonix1** [comment]
Let me know when/if you have something you want me to test! :smile:

**Comment by lonix1** [comment]
👍 This is exciting... Can't wait for the plugin to be approved, so I can try it!

**Comment by lastlink** [comment]
They are way faster in their approval than chrome. I've posted the links in the readme already. https://addons.mozilla.org/en-US/firefox/addon/git-kanban-enhanced-selfhosted/. I had to majorly refactor my build tools for mozilla support. It did decrease my build size tremendously from 6mb to ~150kb with very minor changes in the actual code logic. One of the reasons for the refactor was firefox didn't like my vendor.js being 5mb and wanted each file to be at least smaller than 4mb so I looked into bundle code splitting which webpack 3 didn't support natively, but webpack 4 does.

 The development process should be clearer now in the readme if you'd like to contribute. Basically only the kanban in gitea is functional now. I want to **extend** on the kanbans in the others.

**Comment by lastlink** [comment]
I think the key changes is I had to update how the rest calls were made for firefox to work `/` root didn't work so I had to add window.location.host. The other changes we talked about earlier about the `chrome.` api extensions I didn't need to change b/c I found a polyfill that is now included in my build process.
